<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="transducer">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <xacro:macro name="transducer" params="connected_to:='' arm_id:='panda' rpy:='0 0 0' xyz:='0 0 0' safety_distance:=0 gazebo:=false description_pkg:=franka_description">
    
    <xacro:unless value="${connected_to == ''}">
      <joint name="${arm_id}_hand_joint" type="fixed">
        <parent link="${connected_to}" />
        <child link="${arm_id}_transducer" />
        <origin xyz="${xyz}" rpy="${rpy}" />
      </joint>
    </xacro:unless>

    <xacro:link_with_sc name="transducer" gazebo="${gazebo}">
      <self_collision_geometries>
        <xacro:collision_capsule xyz="0 0 0.04" direction="y" radius="${0.04+safety_distance}" length="0.1" />
        <xacro:collision_capsule xyz="0 0 0.10" direction="y" radius="${0.02+safety_distance}" length="0.1" />
      </self_collision_geometries>
    </xacro:link_with_sc>

    <!-- Define the hand_tcp frame -->
    <link name="${arm_id}_transducer_tcp" />
    <joint name="${arm_id}_transducer_tcp_joint" type="fixed">
      <origin xyz="0 0 0.1034" rpy="0 0 0" />
      <parent link="${arm_id}_transducer" />
      <child link="${arm_id}_transducer_tcp" />
    </joint>
    
  </xacro:macro>
</robot>
